version: "3.4"

services:
  frontend:
    image: classtranscribe/frontend:latest
    env_file:
      .env
    depends_on:
      - traefik
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.backend=frontend"
      - "traefik.port=80"
      - "traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE:-}PathPrefix: /"
      - "traefik.website.frontend.whiteList.sourceRange=${TRAEFIK_IPFILTER:-172.16.0.0/12}"
    container_name: "frontend"

# ----------------------------------------------------------------------
# Volumes used ClassTranscribe
# ----------------------------------------------------------------------
# if you change any of the volumes you will need the volumes header.
volumes:

  # use a local subfolders in data folder to store the volumes.
  traefik:
    driver_opts:
      type: none
      device: ${DATA:-~/docker_data}/traefik
      o: bind
  pgvolume:
    driver_opts:
      type: none
      device: ${DATA:-~/docker_data}/pgvolume
      o: bind
  pga4volume:
    driver_opts:
      type: none
      device: ${DATA:-~/docker_data}/pga4volume
      o: bind
  rabbitmq:
    driver_opts:
      type: none
      device: ${DATA:-~/docker_data}/rabbitmq
      o: bind
  portainer:
    driver_opts:
      type: none
      device: ${DATA:-~/docker_data}/portainer
      o: bind
  data:
    driver_opts:
      type: none
      device: ${DATA:-~/docker_data}/data
      o: bind
