version: "3.4"

services:
  frontend:
    image: node
    volumes:
      - ./FrontEnd:/frontend
      - /frontend/node_modules
    env_file:
      .env
    container_name: "frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=frontend"
      - "traefik.port=3000"
      - "traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE:-}PathPrefix: /"
      - "traefik.website.frontend.whiteList.sourceRange=${TRAEFIK_IPFILTER:-172.16.0.0/12}"
    command: /bin/sh -c "cd frontend; yarn; yarn install; yarn start"
  
  api:
    image: api
    build:
      context: ./WebAPI
      target: publish
      dockerfile: ./API.Dockerfile
    volumes:
      - type: bind
        source: ../data
        target: /data
  
  noderpcserver:
    image: rpcserver
    build:
      context: ./WebAPI
      dockerfile: ./rpcserver.Dockerfile
    volumes:
        - type: bind
          source: ../data
          target: /data
  
  pythonrpcserver:
    image: rpcserver
    build:
      context: ./WebAPI
      dockerfile: ./rpcserver.Dockerfile
    volumes:
        - type: bind
          source: ../data
          target: /data
  
  taskengine:
    image: taskengine
    build:
      context: ./WebAPI
      target: publish
      dockerfile: ./TaskEngine.Dockerfile
    volumes:
      - type: bind
        source: ../data
        target: /data