version: "3.4"

services:  
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=frontend"
      - "traefik.port=3000"
      - "traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE:-}PathPrefix: /"
      - "traefik.website.frontend.whiteList.sourceRange=${TRAEFIK_IPFILTER:-172.16.0.0/12}"
    command: /bin/sh -c "cd frontend; yarn; yarn install; yarn start"