version: "3.4"

services:
    env_generator:
        image: env_generator
        build:
            context: .
            dockerfile: ./ENV_GENERATOR.Dockerfile
        volumes:
            - ".:/curr_dir"
        command: "bash -c /curr_dir/env_generator.sh"
