version: "3.4"

services:
  frontend:
    image: node:lts    
    volumes:
      - ./FrontEnd:/frontend
      - /frontend/node_modules
    env_file:
      .env
    container_name: "frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=frontend"
      - "traefik.port=3000"
      - "traefik.frontend.rule=PathPrefix: /"
      - "traefik.website.frontend.whiteList.sourceRange=${TRAEFIK_IPFILTER:-172.16.0.0/12}"
    command: /bin/sh -c "cd frontend; yarn; yarn install; yarn start"
  
  pythonrpcserver:    
    volumes:
      - "${DATA:-~/docker_data}/data:/data"

  rabbitmq:
    ports:
      - "5672:5672"
